name: Upload to PyPI

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    upload:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: "Install dependencies"
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install build twine

            - name: "Build package"
              run: python3 -m build

            - name: "Upload to PyPI"
              run: python3 -m twine upload dist/*
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
